/*******************************************************************************
 * Copyright (c) 2011 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package com.ibm.websphere.simplicity.commands.eventservicedb;

import java.util.Properties;
import java.util.List;
import com.ibm.websphere.simplicity.Scope;
import com.ibm.websphere.simplicity.OperationResults;
import com.ibm.websphere.simplicity.commands.Command;

/**
 * NOTE: Please do not use this command unless a Simplicity API does not already exist.
 * The removeEventServiceInformixDB command removes the Event Service database and data sources for Informix from a server or cluster.
 *   'removeDB': The command removes the database when this parameter is set to true and does not remove the database when set to false. To remove the database, the current machine must already configured to run the database commands.
 *   'nodeName': The name of the node that contains the server where the Event Service data source should be removed. If this parameter is specified, then the serverName parameter must be set. You must not specify this parameter if the clusterName parameter is specified.
 *   'serverName': The name of the server where the Event Service data source should be removed. If this parameter is specified without the nodeName parameter, the command will use the node name of the current WebSphere profile. You must not specify this parameter if the clusterName parameter is specified.
 *   'clusterName': The name of the cluster where the Event Service data source should be removed. If this parameter is specified, then the serverName and nodeName parameters must not be set. You must not specify this parameter if the serverName and nodeName parameters are specified.
 *   'dbScriptDir': The directory containing the database scripts generated by the Event Service database configuration command. If specified, the command will run the scripts in this directory to remove the Event Service database. The default path is $profile/databases/event/&lt;node&gt;/&lt;server&gt;/dbscripts directory if not specified.
 * The required parameters are found in the constructor.
 */
public class RemoveEventServiceInformixDB extends Command {

	private Boolean removeDB = false;
	private String nodeName;
	private String serverName;
	private String clusterName;
	private String dbScriptDir;

	public RemoveEventServiceInformixDB() {
		super("removeEventServiceInformixDB");
	}

	/**
	 * The command removes the database when this parameter is set to true and does not remove the database when set to false. To remove the database, the current machine must already configured to run the database commands.
	 */
	public Boolean getRemoveDB() {
		return this.removeDB;
	}

	/**
	 * The command removes the database when this parameter is set to true and does not remove the database when set to false. To remove the database, the current machine must already configured to run the database commands.
	 */
	public void setRemoveDB(Boolean value) {
		this.removeDB = value;
	}

	/**
	 * The name of the node that contains the server where the Event Service data source should be removed. If this parameter is specified, then the serverName parameter must be set. You must not specify this parameter if the clusterName parameter is specified.
	 */
	public String getNodeName() {
		return this.nodeName;
	}

	/**
	 * The name of the node that contains the server where the Event Service data source should be removed. If this parameter is specified, then the serverName parameter must be set. You must not specify this parameter if the clusterName parameter is specified.
	 */
	public void setNodeName(String value) {
		this.nodeName = value;
	}

	/**
	 * The name of the server where the Event Service data source should be removed. If this parameter is specified without the nodeName parameter, the command will use the node name of the current WebSphere profile. You must not specify this parameter if the clusterName parameter is specified.
	 */
	public String getServerName() {
		return this.serverName;
	}

	/**
	 * The name of the server where the Event Service data source should be removed. If this parameter is specified without the nodeName parameter, the command will use the node name of the current WebSphere profile. You must not specify this parameter if the clusterName parameter is specified.
	 */
	public void setServerName(String value) {
		this.serverName = value;
	}

	/**
	 * The name of the cluster where the Event Service data source should be removed. If this parameter is specified, then the serverName and nodeName parameters must not be set. You must not specify this parameter if the serverName and nodeName parameters are specified.
	 */
	public String getClusterName() {
		return this.clusterName;
	}

	/**
	 * The name of the cluster where the Event Service data source should be removed. If this parameter is specified, then the serverName and nodeName parameters must not be set. You must not specify this parameter if the serverName and nodeName parameters are specified.
	 */
	public void setClusterName(String value) {
		this.clusterName = value;
	}

	/**
	 * The directory containing the database scripts generated by the Event Service database configuration command. If specified, the command will run the scripts in this directory to remove the Event Service database. The default path is $profile/databases/event/&lt;node&gt;/&lt;server&gt;/dbscripts directory if not specified.
	 */
	public String getDbScriptDir() {
		return this.dbScriptDir;
	}

	/**
	 * The directory containing the database scripts generated by the Event Service database configuration command. If specified, the command will run the scripts in this directory to remove the Event Service database. The default path is $profile/databases/event/&lt;node&gt;/&lt;server&gt;/dbscripts directory if not specified.
	 */
	public void setDbScriptDir(String value) {
		this.dbScriptDir = value;
	}

	public Properties __getParameters() {
		Properties ret = new Properties();
		if (this.removeDB != null) {
			ret.put("removeDB", this.removeDB);
		}
		if (this.nodeName != null) {
			ret.put("nodeName", this.nodeName);
		}
		if (this.serverName != null) {
			ret.put("serverName", this.serverName);
		}
		if (this.clusterName != null) {
			ret.put("clusterName", this.clusterName);
		}
		if (this.dbScriptDir != null) {
			ret.put("dbScriptDir", this.dbScriptDir);
		}
		return ret;
	}

	public Object __getTarget() {
		return null;
	}

	public List<Command> __getSteps() {
		return null;
	}

	/**
	 * Executes the command against the specified scope.
	 */
	public OperationResults<Object> run(Scope scope) throws Exception {
		return super.run(scope);
	}

}
