/*******************************************************************************
 * Copyright (c) 2011 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package com.ibm.websphere.simplicity.commands.idmgrrepositoryconfig;

import java.util.Properties;
import java.util.List;
import com.ibm.websphere.simplicity.Scope;
import com.ibm.websphere.simplicity.OperationResults;
import com.ibm.websphere.simplicity.commands.Command;

/**
 * NOTE: Please do not use this command unless a Simplicity API does not already exist.
 * Adds a configuration for an LDAP attribute used as an external ID.
 *   'id': The unique identifier of the repository.
 *   'name': The name of the LDAP attribute.
 *   'syntax': The syntax of the LDAP attribute.
 *   'wimGenerate': Whether or not the value of the LDAP attribute should be generated by virtual member manager. If this property is set to true, virtual member manager will generate a globally unique id for the external id attribute.
 *   'entityTypes': The name of the LDAP entity type or a semicolon separated list of LDAP entity types.
 * The required parameters are found in the constructor.
 */
public class AddIdMgrLDAPExternalIdAttr extends Command {

	private String id;
	private String name;
	private String syntax = "string";
	private Boolean wimGenerate = false;
	private String entityTypes;

	public AddIdMgrLDAPExternalIdAttr(String id, String name) {
		super("addIdMgrLDAPExternalIdAttr");
		this.id = id;
		this.name = name;
	}

	/**
	 * The unique identifier of the repository.
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * The unique identifier of the repository.
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * The name of the LDAP attribute.
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * The name of the LDAP attribute.
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * The syntax of the LDAP attribute.
	 */
	public String getSyntax() {
		return this.syntax;
	}

	/**
	 * The syntax of the LDAP attribute.
	 */
	public void setSyntax(String value) {
		this.syntax = value;
	}

	/**
	 * Whether or not the value of the LDAP attribute should be generated by virtual member manager. If this property is set to true, virtual member manager will generate a globally unique id for the external id attribute.
	 */
	public Boolean getWimGenerate() {
		return this.wimGenerate;
	}

	/**
	 * Whether or not the value of the LDAP attribute should be generated by virtual member manager. If this property is set to true, virtual member manager will generate a globally unique id for the external id attribute.
	 */
	public void setWimGenerate(Boolean value) {
		this.wimGenerate = value;
	}

	/**
	 * The name of the LDAP entity type or a semicolon separated list of LDAP entity types.
	 */
	public String getEntityTypes() {
		return this.entityTypes;
	}

	/**
	 * The name of the LDAP entity type or a semicolon separated list of LDAP entity types.
	 */
	public void setEntityTypes(String value) {
		this.entityTypes = value;
	}

	public Properties __getParameters() {
		Properties ret = new Properties();
		ret.put("id", this.id);
		ret.put("name", this.name);
		if (this.syntax != null) {
			ret.put("syntax", this.syntax);
		}
		if (this.wimGenerate != null) {
			ret.put("wimGenerate", this.wimGenerate);
		}
		if (this.entityTypes != null) {
			ret.put("entityTypes", this.entityTypes);
		}
		return ret;
	}

	public Object __getTarget() {
		return null;
	}

	public List<Command> __getSteps() {
		return null;
	}

	/**
	 * Executes the command against the specified scope.
	 */
	public OperationResults<Object> run(Scope scope) throws Exception {
		return super.run(scope);
	}

}
